### PR TITLE
Web app

### PR DESCRIPTION
**Pull request by kepta**
Basic HTML structure and fetching of JSON data
@cdeil 
You can currently look live here https://kepta.github.io/web-experiments
Work in progress

### CODE REVIEW

**Comment by cdeil** [comment]
@kepta - Wow .. you've been busy!

I'll start learning React and the other tools you're using in the coming weeks.

Concerning the page: I'm not sure the navbar at the top and / or the sidebar on the left are really needed.
It depends on how far you / we go with this page ... if it's just to display some 2FHL catalog info, then a single search field and display area are all that's needed. If more info is added (images, other catalogs), probably navbar and / or sidebar to browse the content is needed.

So for this demo page: feel free to structure the page as you like!
I.e. if you want, you can leave it as-is, or simplify it.
And let me know if you have any questions ...

**Comment by cdeil** [comment]
FYI: I managed to install and run the app locally, by following your instructions in the README.
Thanks for adding info there!

The main issue I has was that `jspm install` failed at different points (all timeouts I think) and I had to run it ~ 5 times until it succeeded.

One thing that's not clear to me is when I can / should open up the top-level `index.html` and when `build/index.html`!?
Could you add a sentence or two here?
https://github.com/gammapy/web-experiments#running

**Comment by cdeil** [comment]
Can you please rename `fit_dump.py` to `fits_dump.py`?
The file format is called FITS, and usually the files end in `.fits`.
It's just because MS DOS 20 years ago only supported three characters for file extensions that `.fit` was also used (and by some people still is, sigh).

And please add a one-line comment at the top of the script what it is, e.g.

```
"""
Dump FITS format data to JSON format for display on website.
"""
```

**Comment by kepta** [comment]
@cdeil I have updated the app to now show the tables.
Can you have a look and give me some feedback.

TODO:
- [ ]  Comment the code

**Comment by cdeil** [comment]
This looks great, thanks!
It's what I had in mind when we talked about it.

Here's a few questions / suggestions:
- Document what `.publish` is in the README
- Add a footer that has a link back to this Github repo and maybe a sentence "this is a demo app"
- The source name input field is maybe not the best way if there are 100s of selections? Maybe a [datalist](http://stackoverflow.com/questions/6865943/html-form-select-option-vs-datalist-option] that filters down and displays ~ 10 sources max when I type "J173..." would be better?

**Comment by kepta** [comment]
- [x] Document what .publish is in the README
- [x] Add a footer that has a link back to this Github repo 
- [x] Use datalist

**Comment by kepta** [comment]
@cdeil I have made the changes, let me know what is missing,
after this, what should I work on ?
and the json script, is it done?

**Pull request merged**
